version: '2'

services:
  minecraft:
    image: seuf/minecraft:1.11.2
    hostname: minecraft
    container_name: minecraft
    volumes:
      - '/data/minecraft/world:/usr/share/minecraft/world'
    expose:
      - "25565"
    ports:
      - "25565:25565"
    restart: always
    labels:
      - "traefik.enable=false"
